#@ load("@ytt:data", "data")

#@ if data.values.tanzuAddonsManager.createNamespace:
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.tanzuAddonsManager.namespace
#@ end
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tanzu-addons-manager
  name: tanzu-addons-manager-sa
  namespace: #@ data.values.tanzuAddonsManager.namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-addons-manager-clusterrole
rules:
- apiGroups:
  - run.tanzu.vmware.com
  resources:
  - tanzukubernetesreleases
  - tanzukubernetesreleases/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kubeadmcontrolplanes
  - kubeadmcontrolplanes/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kappctrl.k14s.io
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-addons-manager-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-addons-manager-clusterrole
subjects:
- kind: ServiceAccount
  name: tanzu-addons-manager-sa
  namespace: #@ data.values.tanzuAddonsManager.namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tanzu-addons-manager
  name: tanzu-addons-controller-manager
  namespace: #@ data.values.tanzuAddonsManager.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tanzu-addons-manager
  template:
    metadata:
      labels:
        app: tanzu-addons-manager
    spec:
      containers:
      - args:
        - --metrics-addr=0
        - --enable-leader-election=false
        - #@ "--health-addr=:{}".format(data.values.tanzuAddonsManager.deployment.healthzPort)
        image:  #@ "{}/{}:{}".format(data.values.imageInfo.imageRepository, data.values.imageInfo.images.tanzuAddonsManagerImage.imagePath, data.values.imageInfo.images.tanzuAddonsManagerImage.tag)
        imagePullPolicy: #@ data.values.imageInfo.imagePullPolicy
        name: tanzu-addons-controller
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 40Mi
        ports:
          - containerPort: #@ data.values.tanzuAddonsManager.deployment.healthzPort
            name: healthz
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        startupProbe:
          httpGet:
            path: /healthz
            port: healthz
          failureThreshold: 60
          periodSeconds: 10
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      serviceAccount: tanzu-addons-manager-sa
      terminationGracePeriodSeconds: 10
      #@ if/end data.values.tanzuAddonsManager.deployment.hostNetwork:
      hostNetwork: true
      #@ if/end data.values.tanzuAddonsManager.deployment.priorityClassName:
      priorityClassName: #@ data.values.tanzuAddonsManager.deployment.priorityClassName
      #@ if hasattr(data.values.tanzuAddonsManager.deployment, 'tolerations') and data.values.tanzuAddonsManager.deployment.tolerations:
      tolerations: #@ data.values.tanzuAddonsManager.deployment.tolerations
      #@ end
