#@data/values
#@overlay/match-child-defaults missing_ok=True

---
imageInfo:
  imageRepository: projects-stg.registry.vmware.com/tkg
  imagePullPolicy: IfNotPresent
  images:
    tanzuAddonsManagerImage:
      imagePath: vkatam/addons-controller
      tag: v1.4.0-pre-alpha-2-29-ged4c177
tanzuAddonsManager:
  namespace: tanzu-system
  createNamespace: true
  deployment:
    hostNetwork: false
    priorityClassName: null
    healthzPort: 18316
